### ISSUE TITLE
Add a list of articles

### ISSUE THREAD

**Issue by aerabi** [aerabi/git-weekly-docker-extension#1]
The list of Git Weekly articles is available [here](https://github.com/aerabi/git-weekly) as a Markdown file.

The first iteration would be just to load this Markdown file and render it in the React frontend.

**Comment by isaacmtp** [comment]
i'll do this please

**Comment by aerabi** [comment]
Awesome! I assigned it to you, @isaacmtp. Happy coding! 🎉

**Comment by aerabi** [comment]
Any progress on this PR, @isaacmtp?
